---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks.git
      rev: "v5.0.0"
      hooks:
          - id: check-merge-conflict
          - id: check-executables-have-shebangs
          - id: check-yaml
          - id: end-of-file-fixer
    # Linters
    - repo: https://github.com/adrienverge/yamllint.git
      rev: "v1.35.1"
      hooks:
          - id: yamllint
    - repo: https://github.com/DavidAnson/markdownlint-cli2.git
      rev: "v0.14.0"
      hooks:
          - id: markdownlint-cli2
            args: ["--config .markdownlint.yaml"]
    - repo: https://github.com/ansible-community/ansible-lint.git
      rev: "v24.9.2"
      hooks:
          - id: ansible-lint
