---
- name: Copy PVE SSL certificate chain and key to /etc/ssl
  ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      mode: 0640
  with_items:
      - dest: "{{ lldap_data_dir }}/key.pem"
        content: "{{ lldap_ldaps_private_key }}"
      - dest: "{{ lldap_data_dir }}/cert.pem"
        content: "{{ lldap_ldaps_certificate }}"
